server:
  port: 8082

spring:
  application:
    name: ms-associate
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/associate
    username: postgres
    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      consumer:
        bootstrap-servers: localhost:9092
        group-id: grouptwo_id
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

topic:
  associate-topic: remove_association
  update-topic: update_party
  update-associate: update_associate